### ISSUE TITLE
How to change the intergral boundary?

### ISSUE THREAD

**Issue by Miaoing** [hoshino042/NormalIntegration#2]
The method gives very nice results. 
If I have a perspective depth map prior in camera space, how could I use it as integration boundary?

**Comment by xucao-42** [comment]
Hi, thanks for your interest in our project.
To impose known depth values (no matter dense or sparse) as a constraint, a straightforward way is to add a regularization term to the L2 objective function. 

`min_{z, d}  ||A[z d]^\top||_2^2 + w||M(z-z_prior)||_2^2 `
where w is a weighting factor balancing the normal integration term and the depth prior term, z_prior is a vector of the same length as z. But we do not need to specify all values in z_prior. Because the M = diag(m) masks known depths, where m is a binary vector that indicates the existence of depth values at each pixel within the normal integration domain.



For implementation, suppose you store the perspective depth map as `data.depth_prior` and the corresponding depth mask as `data.depth_mask` and set the weighting factor in `setting.w`,
you can paste the following code 


```
  m = data.depth_mask[data.mask]  # shape: (num_normals,) 
  A_depth = hstack([diags(m.astype(float)), np.zeros((num_normals, num_normals))]) # shape: (num_normals, 2 * num_normals)
  b_depth = data.depth_prior[data.mask]  # shape: (num_normals,) 
  A = vstack([A, setting.w * A_depth])  # shape: (num_plane_equations + num_normals, 2 * num_normals)
  b = np.concatenate([np.zeros(num_plane_equations), w * b_depth])  # shape: (num_plane_equations + num_normals, )
```
after https://github.com/hoshino042/NormalIntegration/blob/4b517424358babc72e5dbf70762eac5e96e81374/methods/perspective_five_point_plane_fitting.py#L85

Then modify the solver 
https://github.com/hoshino042/NormalIntegration/blob/4b517424358babc72e5dbf70762eac5e96e81374/methods/perspective_five_point_plane_fitting.py#L88
as 
`
x, _ = scipy.sparse.linalg.cg(A.T @ A, A.T @ b, tol=1e-7)
`.
The other part in [perspective_five_point_plane_fitting.py](https://github.com/hoshino042/NormalIntegration/blob/main/methods/perspective_five_point_plane_fitting.py) can stay the same.

I haven't verified the above code, so there may be some bugs, but you should get the idea :)

FYI:
You can take a look at [(Nehab et al., 2005)](https://dl.acm.org/doi/abs/10.1145/1073204.1073226) or [(Qu´eau et al., 2018)](https://vision.in.tum.de/_media/spezial/bib/jmiv_integration_2.pdf) for mathematical details.
Based on my experiments, if the prior depth map is sparse but the target surface contains depth discontinuities, imposing depth prior will lead to not nice-looking (i.e., visually distored) shapes. 
If the prior depth map is dense but loses high-frequency details, then the high-frequency details will likely be recovered from the normal map.

**Comment by Miaoing** [comment]
Thanks a lot for your detailed explanation. : )
After days of struggling, this work saves my day.
I tried to give a dense depth prior, and the result is pretty good! So cool!!!

The code works fine, with only one line to be modified:
```x, _ = scipy.sparse.linalg.cg(A.T @ A, A.T @ b, tol=1e-7)```
x need to be reshape to (n ,1) from (n,)
```x = x[..., None]```
